Repository The-Code-In-Sheep-s-Clothing/bogl, pull requests merged in 2020-01, with the labels that each got.

#12 call-by-value
  src/Runtime/Eval.hs
Labels: requested change

#22 Adds Travis CI
  .travis.yml
Labels: wip

#21 JSON serialization
  package.yaml
  src/Language/Syntax.hs
  src/Runtime/Serializer.hs
  test/Tests.hs
Labels: enhancement
